version: '3'

services: 
    api: 
        image: php:7.4-apache
        build: .
        container_name: phpSymfony
        environment: 
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        ports: 
            - "9090:80"
        volumes:
            - ./MoviesBackend:/var/www/html 
            - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
    mysql:
        image: mysql:8.0
        container_name: mysqlSymfony
        environment: 
            MYSQL_DATABASE: movies
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        restart: always